#!/bin/sh

cmd=$(printf "suspend\nreboot\npoweroff\nlock\nlogout\n" | dmenu -fn "Gohufont:pixelsize=11:antialias=true:autohint=true" $*)

if [ -z "$cmd" ]; then
	exit 0
fi

case "$cmd" in
	poweroff)
		systemctl poweroff ;;
	reboot)
		systemctl reboot ;;
	suspend)
		systemctl suspend ;;
	lock)
		slock ;;
	logout)
		killall X ;;
	*)
		printf "Option not recognized: %s\n" "$cmd" >&2
esac
